func is_prime(n):
  if n == 2 or n == 3:
    return true;
  end

  if n <= 1 or n % 2 == 0 or n % 3 == 0:
    return false;
  end

  var i = 5;
  while i * i <= n:
    if n % i == 0 or n % (i + 2) == 0:
      return false;
    end
    i = i + 6;
  end
  return true;
end

func main():
  final max = 600851475143 / 2;

  var largest = 0;
  for i in [1..max]:
    if is_prime(*i) and *i > largest:
      largest = *i;
    end
  end
  println(largest);
end
