print(True and True)
print(True or False)
print(False and False)
print(1 == 2)
print(10 >= 10)
print(10.0 / 3.0)
print(1 / 2.0)
print(1.0 / 2)

print('a')
print('a' + 'b')
print('0' < '9')
print('\'')
print(1 + 'x')
