declaration   -> classDecl
               | funcDecl
               | varDecl
               | finalDecl
               | statement ;

classDecl     -> "class" IDENTIFIER ":" function* "end" ;
funcDecl      -> "func" function ;
varDecl       -> TYPE IDENTIFIER ( "=" expression )? ";" ;
finalDecl     -> "final" TYPE IDENTIFIER "=" expression ";" ;
