keyword       -> as 
              | class 
              | final 
              | func 
              | meth 
              | for 
              | while 
              | end 
              | if 
              | true 
              | false 
              | this
              | null
              | var
              | final ;
