func main():
  assert(Char(97) == 'a');

  var num = 1234;
  var str = String(num);
  println(str * 3);
  println(Int(str) * 3);

  var l = List(0, 1, 2, "Hello");
  println(l);

  var e = Exception("This is an exception");
  var e2 = Exception(l);

  println(e);
  println(e2);

  var kvp = KeyValuePair("Ryan", 23);
  println(kvp);

  var pair_list = List(kvp, kvp, kvp);
  println(pair_list);

  var d = Dict();
end
