func factorial(num):
  if num < 2:
    return num;
  end
  return num * factorial(num - 1);
end

func main():
  final operatives = ["Hays", "Syl", "Ryan"];

  for operative, index in operatives:
    println("Operative #" + index + " is " + operative);
  end

  println();

  final dict = {
    "Jamie": "Snake",
    "Operative List": operatives,
    factorial(10): factorial(20),
  };

  for key, value in dict:
    println("The key is " + key + " and the value is " + value);
  end
end
