func h():
  var n = 3.14 ** 2.5;
  print("3.14 ** 2.5 = ");
  println(n);

  var aBigNumber = 2 ** 64;
  println(aBigNumber);
  println("h is returning");
end 

func g():
  println("this" + " is " + "function" + " g!");
  print();
  print();
  print();
  println("hey there");
end 

func f():
  println("This is function" + " " + "f");
end 

func main():
  var n = 2 ** 32;
  println(n);
  var b;
  b = 3.0;
  println(b);

  f();
  g();
  h();

  b = "hello world";
  println(b);
end
 
