func export insert(this Dict dict, key, value):
  __NATIVE_DICTIONARY_INSERT(dict, key, value);
end

func export get(this Dict dict, key):
  return __NATIVE_DICTIONARY_GET(dict, key);
end

func export remove(this Dict dict, key) :: Bool:
  return __NATIVE_DICTIONARY_REMOVE(dict, key); 
end

func export contains_key(this Dict dict, key) :: Bool:
  return __NATIVE_DICTIONARY_CONTAINS_KEY(dict, key);
end
